spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        ##Security MICRO-SERVICE
        - id: security
          uri: lb://security
          predicates:
            - Path=/security/**
          filters:
            - StripPrefix=1

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true